name: Docker Build (PR)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "GameOps/src/**"
      - "GameOps/ops/**"
      - "global.json"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./GameOps
          file: ./GameOps/ops/Dockerfile
          push: false
          tags: gameops/app:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max