name: EF Migrations Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - "GameOps/src/**"
      - "GameOps/.config/dotnet-tools.json"
      - "global.json"

jobs:
  ef-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET (from global.json)
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Restore dotnet tools (EF CLI)
        run: dotnet tool restore

      - name: Generate idempotent migration script
        run: |
          mkdir -p artifacts
          dotnet ef migrations script \
            --idempotent \
            --project src/App \
            --startup-project src/App \
            -o artifacts/migrations.sql

      - name: Sanity check SQL not empty
        run: test -s artifacts/migrations.sql

      - name: Upload migration script (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: migrations-sql
          path: artifacts/migrations.sql
