name: CI Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 (from global.json)
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true

      - name: Restore
        run: dotnet restore
        working-directory: GameOps

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore
        working-directory: GameOps

      - name: Restore dotnet tools (EF CLI)
        run: dotnet tool restore --tool-manifest GameOps/.config/dotnet-tools.json

      - name: Generate idempotent migration script
        working-directory: GameOps
        run: |
          mkdir -p artifacts
          dotnet ef migrations script \
            --idempotent \
            --project src/App \
            --startup-project src/App \
            -o artifacts/migrations.sql

      - name: Sanity check SQL not empty
        run: test -s GameOps/artifacts/migrations.sql

      - name: Upload migration script (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: migrations-sql
          path: GameOps/artifacts/migrations.sql